### ISSUE TITLE
Support for ABIEncoderV2

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#146]
Add logic to understand the ABI type `tuple` for contract inputs outputs, and events.  Will require edits to:

- [x] `brownie.types.convert._format()`
- [x] `encode_abi` and `decode_abi` class methods in `brownie.network.contract`
- [x] [`eth-event`](https://github.com/iamdefinitelyahuman/eth-event) ([#3](https://github.com/iamdefinitelyahuman/eth-event/issues/3))
- [x] `brownie.network.event`
- [x] write new test cases
- [x] update docs

Related solidity docs: https://solidity.readthedocs.io/en/latest/abi-spec.html#handling-tuple-types

`eth-abi` supports this in version 2.0 but it is still in beta. There is a plan to phase out the `encode_abi` and `decode_abi` methods from this package, so Brownie should instead use `encode_single` and `decode_single`. Until 2.0 is out of beta, consider internally handling the encoding to non-standard packed mode.

**Comment by banteg** [comment]
This could be useful https://github.com/ethereum/web3.py/pull/1353

**Comment by iamdefinitelyahuman** [comment]
Related to #159 - web3py is at 5.0.0 stable, eth-abi at 2.0.0 stable, implementing this should be easy now
