### ISSUE TITLE
Can we use Brownie with geth ?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [iamdefinitelyahuman/brownie#173]
Similar to how Truffle can be used to deploy smart contracts on the Rinkeby testnet through geth, is it possible that we can use Brownie can be used in the same fashion?

i am an absolute beginner so please let me know if i am missing anything ?

P.S : in case if there's absolutely no support for testnets like rinkeby **OR** clients like geth or parity, kindly convert this post into an **Issue**, calling for support to the aforementioned functionalities to be added.

**Comment by iamdefinitelyahuman** [comment]
It's possible, yes, but still needs to be properly documented.  The process is currently buried within the [config file documentation](https://eth-brownie.readthedocs.io/en/latest/config.html#the-configuration-file).

You need to edit the configuration file for your project and point it at your local geth client, or add your own API token if you want to use Infura.  Then when running Brownie, include the `--network` flag to specify which network to connect to.

If you encounter any bugs while working on a non-local network please raise an issue, or feel free to reach out to me on gitter :)

**Comment by iamdefinitelyahuman** [comment]
Related issue - https://github.com/iamdefinitelyahuman/brownie/issues/41

**Comment by iamdefinitelyahuman** [comment]
@SyedMuhamadYasir I've opened another issue to get this properly documented it, and funded it via Gitcoin.  So hopefully it's solved soon!  Going to close this issue now in favor of #174.
