### ISSUE TITLE
Incorrect return type in api-brownie.rst for format_input

### ISSUE THREAD

**Issue by crawfordleeds** [iamdefinitelyahuman/brownie#180]
The [docs](https://eth-brownie.readthedocs.io/en/latest/api-brownie.html#brownie.convert.format_input) currently state that `format_input` returns "Returns a list of values formatted for use by ContractTx or ContractCall."

However, it seems it actually returns an instance of brownie.convert.ReturnValue which inherits from tuple.

I have updated the docs in my PR #170 but was hoping to get a second set of eyes on this to make sure I'm not missing something.

For references, here's the output in my terminal.  

```
>>> from brownie.convert import format_input
>>> abi = {'constant': False, 'inputs': [{'name': '_to', 'type': 'address'}, {'name': '_value', 'type': 'uint256'}], 'name': 'transfer', 'outputs': [{'name': '', 'type': 'bool'}], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'}
>>> format_input(abi, ["0xB8c77482e45F1F44dE1745F52C74426C631bDD52","1 ether"])
('0xB8c77482e45F1F44dE1745F52C74426C631bDD52', 0)
>>> type(format_input(abi, ["0xB8c77482e45F1F44dE1745F52C74426C631bDD52","1 ether"]))
<class 'brownie.convert.ReturnValue'>
```

This all also applies to the `format_output` method.

**Comment by iamdefinitelyahuman** [comment]
I think it's a case of poor documentation, and maybe over-aggressive refactoring.

* `format_input` performs type and bound checks, and standardizes formatting of user given data, before that data is encoded and used to call a contract.
* `format_output` uses near identical logic to standardize the output from a contract call or transaction before returning it to the user.

Neither of these methods are intended to be called directly, they're used under the hood by `_ContractMethod` subclasses.  There is significant overlap in the logic of these functions, so to minimize duplicated code they are both returning a `ReturnValue` object.  I hadn't considered a user ever calling `format_input` directly and discovering the peculiar name of it's return type :astonished: 

My thought here is that both of these methods (as well as `format_event`) should be made private.  Users can still convert data through the various `to_xxx` methods in `brownie.convert` if needed.  Alternatively, we could modify `format_input` to return a list or tuple so it's less confusing.

Thoughts?

**Comment by crawfordleeds** [comment]
I figured it was just a delay in updating the documentation. I think the code is fine exactly as is, the documentation just needs to be updated. PR #170 updates the documentation accordingly.

Sounds like the only advantage of making these private methods is just to be more explicit about the fact that these are not intended to be called directly? I'd be in support of that as a case could be made that the docs are a bit misleading on this by including an example to use the methods directly. Otherwise, I don't think it matters much. I like returning a `ReturnValue` object just fine.

Let's make a separate issue to make `format_input` `format_output` and `format_event` private methods. Otherwise, I think this issue can be closed once #170 gets merged.

**Comment by iamdefinitelyahuman** [comment]
I think this might be the start of a much broader discussion...  there is a lot of stuff in the docs that i mention as "you probably don't ever need to import or call this directly" - before taking the beta tag off, it would be good to add some underscores and explicitly make a lot of the API private.  Then the docs can include a new sub-section "private methods" or "internal methods" so the information is still there when people are hacking on brownie itself, but it's also more clear to casual users that here be dragons...

**Comment by crawfordleeds** [comment]
Okay good point I'll take another look at the docs in this context and see if I can think of a precise way to handle this.

**Comment by iamdefinitelyahuman** [comment]
I already do it a bit..  `_config.py`, `_singleton.py` - those are prepended to clearly tell people to stay out. There are probably a lot of other modules where none of the functionality is meant to face the user and rather than renaming a lot of methods we could just rename the whole file.
