### ISSUE TITLE
`height` in Accounts._revert(self, height) unused

### ISSUE THREAD

**Issue by crawfordleeds** [iamdefinitelyahuman/brownie#194]
In looking at the `_revert` method of the Accounts singleton, it appears like the only argument, `height` is unused in the method.

https://github.com/iamdefinitelyahuman/brownie/blob/ec3544027441b87a6f3a87cbf1c65b4faac617c0/brownie/network/account.py#L45-L47

We should probably remove that unused argument and adjust the implementation of that method where applicable.

**Comment by iamdefinitelyahuman** [comment]
Classes with a `_revert` method are registered in `Rpc` via `Rpc._revert_register`, then called via `_revert` (or `_reset`) whenever the chain is reverted to a previous state.  In the case of `Accounts` the information about the height isn't needed, but other classes such as `ContractContainer` and `TxHistory` require it.

The logic for maintaining an accurate picture of "now" after a revert isn't documented anywhere...  at some point things like this should probably be written down.
