### ISSUE TITLE
Token example error

### ISSUE THREAD

**Issue by manfr3d** [iamdefinitelyahuman/brownie#239]
* `brownie` Version: 1.0.1
* `ganache-cli` Version: 6.7.0
* `solc` Version: 0.5.12
* Python Version: 3.7.0
* OS: win

### What was wrong?

Please include information like:

* full output of the error you received

> brownie bake token
> brownie compile
> brownie console
Brownie v1.0.1 - Python development framework for Ethereum

TokenProject is the active project.
Launching 'ganache-cli.cmd --port 8545 --gasLimit 6721975 --accounts 10 --hardfork petersburg --mnemonic brownie'...
Brownie environment is ready.

>>> accounts[0]
<Account object '0x66aB6D9362d4F35596279692F0251Db635165871'>
>>> accounts[0].balance()
100000000000000000000

>>> t = Token.deploy(accounts[1], "Test Token", "TST", 18, "1000 ether")
  File "<console>", line 1, in <module>
  File "c:\python37\lib\site-packages\brownie\network\contract.py", line 169, in __call__
    "Contract has no owner, you must supply a tx dict"
AttributeError: Contract has no owner, you must supply a tx dict with a 'from' field as the last argument.

* what command you ran
Token.deploy(...)

* the code that caused the failure

Token from 
https://eth-brownie.readthedocs.io/en/latest/quickstart.html

Thanks!

**Comment by iamdefinitelyahuman** [comment]
Thank you for opening an issue and bringing this to my attention! The proper syntax is:

```python
t = Token.deploy("Test Token", "TST", 18, "1000 ether", {'from': accounts[1]})
```

I will push a fix shortly.

**Comment by manfr3d** [comment]
Thank you!

**Comment by iamdefinitelyahuman** [comment]
Small update -  the doctest CI build is currently failing because of an expired SSL cert. Once that is fixed I will merge, if it isn't dealt with soon I can replace the broken link with the github version at https://github.com/miguelmota/ethereum-development-with-go-book/tree/master/en/keystore
