### ISSUE TITLE
Testing structs with Brownie

### ISSUE THREAD

**Issue by manfr3d** [iamdefinitelyahuman/brownie#241]
* `brownie` Version: 1.0.1
* `ganache-cli` Version: 6.7.0
* `solc` Version: 0.5.12+commit.7709ece9.Windows.msvc
* Python Version: 3.7.0
* OS: win

### What was wrong?

I am trying to test structs but I don't know how to do it on Brownie.

For example, I tried inside pytest module:

`SomeRandomContract.MyStructInsideTheContract(10,100)
`
And I get something like this:

`EventMasterService = []
accounts = [<Account object '0x66aB6D9362d4F35596279692F0251Db635165871'>, <Account object '0x33A4622B82D4...7c1AF08B8831795FAC946025557369F69C'>, <Account object '0x1CEE82EEd89Bd5Be5bf2507a92a755dcF1D8e8dc'>]

    @pytest.fixture(scope="module", autouse=True)
    def event_data(EventMasterService, accounts):
>       ed = EventMasterService.EventData()
E       AttributeError: 'ContractContainer' object has no attribute 'EventData'

tests\test_events.py:34: AttributeError`

Without as Python and Brownie are not giving exposure to the structs. Am I missing something?

Thanks in advance, I have written around ~100 tests in Brownie, so far very happy. :D

**Comment by manfr3d** [comment]
Okey, I found that at least I can use a helper in Solidity to construct the examples for testing:

Something like this:

`contract test{

    ArbitrableBlacklist.Item public item;

    function create() public {
        item = ArbitrableBlacklist.Item({
           status: ArbitrableBlacklist.ItemStatus.Absent,
           lastAction: 0
        });
    }

}`

https://stackoverflow.com/questions/50746393/how-to-initialize-a-struct-from-javascript-when-testing-a-solidity-contract

**Comment by iamdefinitelyahuman** [comment]
Hi :) Glad to hear Brownie has been good for you so far!

From the error message:
```python
AttributeError: 'ContractContainer' object has no attribute 'EventData'
```
It seems you are trying to call a function named `EventData` within your contract, but you haven't actually deployed the contract yet.  Try using `EventMasterService.deploy` to deploy a specific instance of the contract, and then call the method on that instance.

The section of the documentation on [contract interaction](https://eth-brownie.readthedocs.io/en/latest/interaction.html#contracts) might be helpful for you.

I'll keep this issue open, if you have any further questions don't hesitate to ask :)  Or you can find me on [Gitter](https://gitter.im/eth-brownie/community).
