### ISSUE TITLE
Running a script from a test case

### ISSUE THREAD

**Issue by vadimkerr** [iamdefinitelyahuman/brownie#252]
* brownie Version: 1.1.0
* ganache-cli Version: 6.7.0
* solc Version: 0.5.13
* Python Version: 3.7.3
* OS: linux

I wanted to run a script from a test case via `projects.scripts.run` but got the following error:
```
ValueError: '/home/user/project/scripts/deploy_ERC820_registry.py' does not start with '/home/user/project/tests'
```

I think it's some problem with path handling, the function call that is causing the exception is
```
path = Path(path).absolute().relative_to(sys.path[0])
```
inside `_import_from_path` method of `brownie.project.scripts`

**Comment by iamdefinitelyahuman** [comment]
WIP at [brownie/scripts-run](https://github.com/iamdefinitelyahuman/brownie/compare/scripts-run)
