### ISSUE TITLE
Pytest outputs the entire contract source when no useful highlight is available

### ISSUE THREAD

**Issue by manfr3d** [iamdefinitelyahuman/brownie#255]
* `brownie` Version: 1.1.0
* `ganache-cli` Version: 0.6.7
* `solc` Version: 0.5.12
* Python Version: 3.7.0
* OS: win

## What was wrong?

When I change a function from "payable" to non-"payable" and I forget to remove the "value" from testing transaction the error message is just a Revert and is dumping the whole source code of the contract. I was hoping a more helpful message will be printed if this condition can be detected:

$ pytest ./tests/sometest.py

### with payable this test is okey

    my_service.buySomething({'from': accounts[0], 'value': 300})

### I forgot to remove the  'value': 300 parameter, only works for payable.

    my_service.buySomething({'from': accounts[0], 'value': 300})

.....

### after working my head around the output I remove the value parameter.

    my_service.buySomething({'from': accounts[0]})

Thanks in advance.

OUTPUT:

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\python37\lib\site-packages\brownie\network\contract.py:434: in __call__
    return self.transact(*args)
c:\python37\lib\site-packages\brownie\network\contract.py:382: in transact
    data=self.encode_input(*args),
c:\python37\lib\site-packages\brownie\network\account.py:319: in transfer
    return TransactionReceipt(txid, self, revert_data=revert_data)
c:\python37\lib\site-packages\brownie\network\transaction.py:173: in __init__
    self._traceback_string() if ARGV["revert"] else self._error_string(1),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

msg = 'revert '
source = '\x1b[0;2;37mTrace step \x1b[0;1;34m3\x1b[0;2;37m, program counter \x1b[0;1;34m5\x1b[0;2;37m:\n  \x1b[0;2;37mFile \x1b...r, _from, _to, _ids, _values, _data);\n\x1b[0;m            }\n\x1b[0;m        }\n\n\n\x1b[0;m    }\x1b[0;2;37m\x1b[0;m'

    def _raise(msg: str, source: str) -> None:
>       raise VirtualMachineError({"message": msg, "source": source})
E       brownie.exceptions.VirtualMachineError: revert
E       Trace step 3, program counter 5:
E         File "contracts/events/Events.sol", lines 11-338, in EventMasterService.buyTicketsBatchWithTokens:
.........................
THE COMPLETE SOURCE CODE OF THE CONTRACT.
.........................
E                   }
E               }
E
E
E           }

c:\python37\lib\site-packages\brownie\network\transaction.py:736: VirtualMachineError

**Comment by iamdefinitelyahuman** [comment]
I see two issues here:

1. Brownie should not be printing a source highlight when the highlight == the entire contract. There are checks in place for this already, so it seems you've found a bug.
2. When a transaction fails because of an attempt to send ether to a non-payable function, the error message should be more verbose than simply "reverted". This should be possible.

**Comment by iamdefinitelyahuman** [comment]
Per https://github.com/iamdefinitelyahuman/brownie/issues/255#issuecomment-557187686, I've opened a new issue for improving the error verbosity and renamed this issue to focus on the incorrect source highlight being displayed.

**Comment by iamdefinitelyahuman** [comment]
I just tested in the console, when the highlight == the entire contract, nothing is being displayed.  So can confirm this behavior is specific to pytest.
