### ISSUE TITLE
Installing from git doesn't create any default brownie-config.yaml

### ISSUE THREAD

**Issue by Huge** [iamdefinitelyahuman/brownie#266]
* `brownie` Version: commit 3b3874348e26ec69c8397b3493e1dd2117fed8b8
* `ganache-cli` Version: x.x.x
* `solc` Version: x.x.x
* Python Version: 3.6.3 (venv)
* OS: Linux

### What was wrong?
`brownie --connect ropsten` and all connect efforts..:
![image](https://user-images.githubusercontent.com/111648/69638420-f1ea8100-105a-11ea-87c3-380391834d4c.png)

**Comment by iamdefinitelyahuman** [comment]
Hello :)  You need to set the `WEB3_INFURA_PROJECT_ID` environment variable before you can interact with Infura.  Check out the [documentation](https://eth-brownie.readthedocs.io/en/stable/nonlocal-networks.html#defining-non-local-networks) for more info.

Hope this helps.  If you have more questions I'm available on [Gitter](https://gitter.im/eth-brownie/community), and I'll leave this issue open as well.

**Comment by iamdefinitelyahuman** [comment]
Closing this for now, but feel free to reopen if you have further issues.
