### ISSUE TITLE
Brownie Config throws on missing solc key

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#297]
* `brownie` Version: 1.4.0
* `solc` Version: N/A
* Python Version: 3.7.5
* OS: linux

### What was wrong?
Brownie assumes `solc` will be specified in a projects configuration file, and throws when it is not there:

```bash
$ brownie compile
Brownie v1.4.0 - Python development framework for Ethereum

  File "brownie/_cli/__main__.py", line 57, in main
    importlib.import_module(f"brownie._cli.{args['<command>']}").main()
  File "brownie/_cli/compile.py", line 28, in main
    project.load(project_path)
  File "brownie/project/main.py", line 443, in load
    return Project(name, project_path)
  File "brownie/project/main.py", line 139, in __init__
    self.load()
  File "brownie/project/main.py", line 147, in load
    self._compiler_config = _load_project_compiler_config(self._path, "solc")
  File "brownie/_config.py", line 113, in _load_project_compiler_config
    return config_data["compiler"][compiler]
KeyError: 'solc'
```

### How to fix it
I think it would probably be best if brownie's config files didn't assume any of the keys are there (using some reasonable defaults unless overriden). Also, it would be great if it didn't assume `solc` was a requirement unless it detected it was necessary (for Vyper-only projects), but perhaps that is a different issue.

**Comment by fubuloubu** [comment]
I had to add the following to my `brownie-config.yml` file in order to compile my Vyper contracts:

```yaml
  solc:
    version: 0.6.0
    optimize: false
    runs: 100
    evm_version: istanbul
    minify_source: false
```

**shivers violently**

**Comment by iamdefinitelyahuman** [comment]
Ahh that is a very good find.  Sorry about the forced install :grimacing:
