### ISSUE TITLE
Default .gitignore

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#298]
When generating a project through `brownie init` it should perhaps generate/append to that project's `.gitignore` file for build objects not intended to go under source control

**Comment by iamdefinitelyahuman** [comment]
Could also be good to add a `.gitattributes`:
```
*.sol linguist-language=Solidity
*.vy linguist-language=Python
```

**Comment by fubuloubu** [comment]
yesss
