### ISSUE TITLE
Allow specifying dev-only ethPM packages

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#299]
### What was wrong?
Let's say I want to test my contract system against some popular deployed contract system like ENS or Maker. I should be able to specify contract systems as testing dependencies (perhaps under `brownie-config.yml`) that don't affect my project's manifest, since it's not a requirement for building/deployment.

Perhaps a separate issue: allow installing contract systems for testing, and generating test fixtures for those systems that I can easily interoperate with (an `ENS` or `Maker` test fixture that has references to their component contracts per their own EthPM packages e.g. [`ENS.Registrar`/`ENS.Deed`/etc.](http://explorer.ethpm.com/manifest/QmeooZzPrT2hDWSkhGoyLeSecsSbU26E6RiYfkXfPoug9U) or [`Maker.SaiMom`/`Maker.TubFab`/etc.](http://explorer.ethpm.com/manifest/QmfYGQDSCF4pbxfPVJnLT4hLGD9rwWdhWG8nKkAoLXYo62))

**Comment by iamdefinitelyahuman** [comment]
To the first idea: what about a flag during install that places the package in a different subfolder such as `contracts/ethpm-dev`, and this folder is ignored when generating a manifest?

To the second idea: it's an undocumented feature (:frowning:), but Brownie already allows you to open multiple projects at the same time.  It would be pretty simple to offer another project as a fixture, which would provide access to it's contracts with exactly the syntax you've suggested.  Need to think on how to best implement this.. but the logic is already there.

**Comment by iamdefinitelyahuman** [comment]
This should probably be handled as two separate issues.  Or the 2nd point absorbed into the work happening around #295.
