### ISSUE TITLE
Have newly generated account share seed phrase

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#303]
### What was wrong?
When generating a new keypair, it would be nice if a seed phrase backup was shared so I can save it via whatever means I would typically employ in backing up my keys. Perhaps using this library: https://github.com/trezor/python-mnemonic, which I believe has been audited (please check)

**Comment by iamdefinitelyahuman** [comment]
Related - https://github.com/iamdefinitelyahuman/brownie/issues/59

I'll look at that library, it may be exactly what was missing to implement this.  Thanks!

**Comment by iamdefinitelyahuman** [comment]
New issue: #334
