### ISSUE TITLE
Consider using IPython for brownie console

### ISSUE THREAD

**Issue by fubuloubu** [iamdefinitelyahuman/brownie#305]
IPython is a really great project, it saves history, has advanced features for working with history, tab completion, etc.

Very easy to integrate with, I think you just definite what you want in your environment when you load it.

**Comment by iamdefinitelyahuman** [comment]
Related - #155 

This has been on the roadmap forever it just never made it to the top of the TODO list.

**Comment by fubuloubu** [comment]
It'll take you 5 minutes. I've done it before.
