### ISSUE TITLE
Reduce the config file

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#325]
### Overview
There are a lot of options in `brownie-config.yaml`. This could be bad because:

1. It can be overwhelming / confusing for new users
2. There is a lot of potential variance in Brownie's behavior 

### Specification
- [ ] Remove the `networks` field and create a new CLI section, `brownie networks`, where these settings are defined.
    - [ ] Share network settings across all projects. Allow new networks to be added manually, imported and exported to JSON
    - [ ] Default to automatic gas price and gas limit for non-local networks, 0 gas and block-gas-limit for test networks.
- [x] Make all pytest-specific settings optional. Include them in the documentation but do not require them in the config file.
- [ ] Make compiler settings optional. Default to the latest EVM and determine the solc version from the pragma statement. Document possible config settings and allow the default behavior to be over-ridden.
- [x] Remove options for customizing colors
   - [ ] add single (optional) setting to toggle all color use
- [x] Remove the option to minify source and perform this action by default.

Related to this, there can be some significant refactoring of how `CONFIG` and `ARGV` are handled internally.

### Dependencies
Most of these changes can be made without breaking anything, so long as the configuration fields are made optional without changing their structure.

Some changes, particularly to `network`, probably _should_ eventually break things, so this may not be complete until Brownie `2.0.0`.

**Comment by fubuloubu** [comment]
This could be done in two stages:
1. Add sensible defaults to everything; Allow users to not specify config fields with defaults (next minor release)
2. Remove certain fields entirely that are too verbose (next major release)

Allowing more defaults isn't a breaking change, just needs to be documented.

**Comment by iamdefinitelyahuman** [comment]
Custom color options removed in #350
