### ISSUE TITLE
Couldnt type certain characters in Brownie console

### ISSUE THREAD

**Issue by GraphicalDot** [iamdefinitelyahuman/brownie#369]
### Environment information

* `brownie` Version: 1.6.6
* `ganache-cli` Version: 2.1.2
* `solc` Version: 0.6.0
* Python Version: 3.7
* OS: ubuntu

### What was wrong?
I ran brownie console and surprisingly, I couldn't type alphabet e in the console.
Everything is working fine on Ipython console, Bash console but not on brownie console.
* what command you ran: NA
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code). NA
* full output of the error you received
```
Brownie v1.6.6 - Python development framework for Ethereum

ErcImplementationProject is the active project.
Attached to local RPC client listening at '127.0.0.1:8545'...
Brownie environment is ready.
>>> from browni 
  File "<console>", line 1,
    from browni
                ^
SyntaxError: invalid syntax
>>> 
```

### How can it be fixed?

Fill this in if you know how the bug could be fixed.

**Comment by iamdefinitelyahuman** [comment]
Thanks for letting me know!  This is a very strange error indeed.

Can you try loading the regular python interpreter and running the following commands, and see if you encounter the same issue?

```bash
$ python3
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import code
>>> code.interact()
...
>>> e
```

The brownie console is a wrapper over the [`code`](https://docs.python.org/3.8/library/code.html) library so I'm wondering if the issue might be happening within that library.

**Comment by iamdefinitelyahuman** [comment]
Ok, so we can rule out brownie as the cause of the issue. Maybe something with python's interpreter?

From the highlight in your initial `SyntaxError`:

```
>>> from browni 
  File "<console>", line 1,
    from browni
                ^
SyntaxError: invalid syntax
```

The `^` marker for where the error occured indicates two characters of whitespace where we'd expect the `e` to be. And that you receive an error at all means a newline had to happen.  I'm guessing that pressing `e` is instead generating some character that isn't `e` which isn't renderable, takes up two spaces, and also triggers a newline.

I'm sorry I can't offer much more..  I'd suggest deleting your virtualenv and setting up a fresh one, and if that doesn't help maybe trying a different version of python.

**Comment by iamdefinitelyahuman** [comment]
Closing this from inactivity..  if you have other issues don't hesitate to open a new issue or join the [gitter](https://gitter.im/eth-brownie/community) channel.
