### ISSUE TITLE
Support for --optimize-yul in brownie-config.yaml

### ISSUE THREAD

**Issue by jonathanmalo** [iamdefinitelyahuman/brownie#405]
### Overview
* What you are trying to do
Pass --optimize-yul to solc.
* Why Brownie's current functionality is inadequate to address your goal
Compiling the 0x asset proxy contracts may require the --optimize-yul solc option. To see what I mean, clone the repository https://github.com/jonathanmalo/brownie-0x and run the `refactor.sh` script. This throws an error:
```
CompilerError: Compiler returned the following errors:
YulException: Stack too deep when compiling inline assembly: Variable assetDataOffset is 2 slot(s) too deep inside the stack.
```
Which seems to be related to the inline assembly found in contracts-asset-proxy/contracts/src/MultiAssetProxy.sol. A "Stack too deep" error was corrected with the --optimize-yul option in https://github.com/ethereum/solidity/issues/6392 and this option is set in https://github.com/0xProject/0x-monorepo/blob/development/contracts/asset-proxy/compiler.json#L12. This sol-compiler config file (compiler.json) also suggests that common subexpression elimination (opetion "cse") and "constantOptimizer" may need to be set for successful compile.
In earlier versions of solc, the yul optimizer, which optimizes stack slot allocation for inline assembly, was not enabled by default: https://solidity.readthedocs.io/en/v0.6.6/using-the-compiler.html
```
        // The new Yul optimizer. Mostly operates on the code of ABIEncoderV2
        // and inline assembly.
        // It is activated together with the global optimizer setting
        // and can be deactivated here.
        // Before Solidity 0.6.0 it had to be activated through this switch.
        "yul": false,
        // Tuning options for the Yul optimizer.
        "yulDetails": {
          // Improve allocation of stack slots for variables, can free up stack slots early.
          // Activated by default if the Yul optimizer is activated.
          "stackAllocation": true
        }
```

### Specification
The option could be passed via another field in brownie-config.yaml: `optimize-yul: true` May as well add all optimization options to future proof this type of issue. However, it may be simpler to add support for sol-compiler to brownie for this particular use case.

Thanks for all your help so far.

**Comment by iamdefinitelyahuman** [comment]
Adding support for other optimizer settings in the config file should be fairly straightforward.  I'll have a look at it right away.
