### ISSUE TITLE
Extract private key from keystore file.

### ISSUE THREAD

**Issue by Skyge** [iamdefinitelyahuman/brownie#441]
I am trying to use keystore file to send a transaction, and I find the code is:
```python
with json_file.open() as fp:
    priv_key = web3.eth.account.decrypt(
        json.load(fp), getpass("Enter the password to unlock this account: ")
     }
```
I am not sure when we try to use the function `web3.eth.account.decrypt()`, whether it will connect to a node or not, but I know the package: [eth_account](https://eth-account.readthedocs.io/en/stable/eth_account.html), it just extracts the private locally, so is there a need to use `eth_account` to replace `web3.eth.account` at here?

**Comment by iamdefinitelyahuman** [comment]
There is no need to use `web3` directly.  After adding the keystore to Brownie, you can access it using `Accounts.load`. For example, if you add the keystore using the ID `owner` as shown in the example in #440, you can then import it with:

```
acct = Accounts.load('owner')
```

`acct` is a `LocalAccount` object which has an identical API to the `Account` objects you are already familiar with.

Related documentation:
* [Account Management](https://eth-brownie.readthedocs.io/en/stable/account-management.html)
* [API docs - `Accounts.load`](https://eth-brownie.readthedocs.io/en/stable/api-network.html#Accounts.load)

**Comment by Skyge** [comment]
Ohhh, so even though we use the function `web3.eth.account.decrypt()`, this is a off-line method, it will not connect a node.

**Comment by Skyge** [comment]
Close the issue, cause it seems like the function `web3.eth.account.decrypt()` in the `web3` and  the function `Accounts.decrypt()` in the `eth_account` return the same result.
