### ISSUE TITLE
Move CI from Travis to Github Actions

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#444]
### Overview
Stop using Travis and start using [Github Actions](https://help.github.com/en/actions).

The beautiful thing about Actions is that anyone who forks the repo has access to CI.  They don't need to make an account with a 3rd party site or enable anything...  they don't even need to understand how CI works!

### Specification
Translate `.travis.yml` to the Actions yaml format.

**Comment by Skyge** [comment]
Sounds like great!
