### ISSUE TITLE
Integrate slither and mythril

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#45]
https://github.com/trailofbits/slither
https://github.com/ConsenSys/mythril-classic

Should be relatively straightforward to call both of these from Brownie when running tests.

**Comment by dmuhs** [comment]
Hey man! I'm Dominik from the ConsenSys Diligence team. I do core development on Mythril and MythX (a SaaS that runs tons of security analysis services in the backend). Just today I actually published a stable version of [PythX](https://github.com/dmuhs/pythx). I tried to make it stupidly simple for devs to integrate the [MythX API](https://mythx.io/).

I'd actually love to help build a plugin for Brownie that allows the user to analyze their code for vulnerabilities (something like `brownie analyze`), or a standalone tool. Hit me up at `{firstname}.{lastname}@consensys.net` if you wanna have a chat about it. Maybe we can push the Python ecosystem in Ethereum a bit more if we combine efforts! :rocket:
