### ISSUE TITLE
Add method to quickly increase nonce for an account

### ISSUE THREAD

**Issue by matnad** [iamdefinitelyahuman/brownie#467]
### Overview
Improve the method to increase the nonce for an unlocked account to a desired value.

Use case: Deploy a contract at a specific address (calculated from sender address and nonce).

Currently we have to loop empty transactions which creates a lot of spam in the console (each tx is printed).

### Specification
Naive: I added a PR with an example on how to implement it. 
Better: Ganache support to increase nonce. [See here.](https://github.com/trufflesuite/ganache-cli/issues/736)
Alternative 1: Implement a batch transaction method where we can pass a list of transactions and get a list of receipts back, executing the transactions silently.
Alternative 2: Add a silent argument to the transaction method.

### Dependencies
Maybe https://github.com/trufflesuite/ganache-cli/issues/736

**Comment by iamdefinitelyahuman** [comment]
Ideally this is handled in Ganache , but I'm not sure how long we'll be waiting for that so probably best to assume it isn't an option.

I like the idea and I can see the use case.  But with a dedicated `increase_nonce` function I'm unsure how to the transaction history and `rpc.undo` functionality. Should the empty transactions be included in the history and the undo buffer? Or better to be collectively batched as a single action, somehow? I lean towards the latter but I'm not sure what it looks like.

Exposing `silent` within `Account.transfer` is a very simple solution and makes it easy for the user to run a for loop..  at which point they should be well aware of the consequences of the action re: the history.

**Comment by matnad** [comment]
Agreed. Do you think batching the transactions would have any benefits other than it potentially being one history element? If batching does not lead to a performance increase or another tangible benefit, then I see little reason to implement it. 

In my use case, I need to get the nonce of some addresses to high double / low tripple digit numbers to deploy contracts at addresses with specific properties (like only being 15bytes instead of 20bytes long). I would already be very happy to have `silent` exposed to suppress the console output and if eventually this can be done faster via ganache, that would be awesome!

**Comment by iamdefinitelyahuman** [comment]
:+1: to exposing `silent` for now as the simplest / quickest path :)

**Comment by iamdefinitelyahuman** [comment]
Closed-ish by #472
