### ISSUE TITLE
Add support for Vyper!

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#47]
Current integration TODO list:

- [x] basic compiliation and interaction
- [x] minification
- [x] dependencies
- [x] only recompile if changed
- [x] decimal data type
- [x] statement coverage 
- branch coverage
  - [x] if/else
  - [x] assert
- custom error strings
  - [x] over/underflow checks
  - [x] out-of-bounds array index
  - [x] paying to a nonpayable function
  - [x] modulus 0
- [x] dev revert strings
- [x] updates to GUI
- [x] test cases
- [x] documentation

**Comment by iamdefinitelyahuman** [comment]
This is the list of items that were handled on the Vyper side, now that it's all completed I've removed it from the initial issue message.

- [x] accept compiler input formatted via Solidity's [standard JSON input](https://solidity.readthedocs.io/en/v0.5.10/using-the-compiler.html#input-description)
- [x] return output formatted via Solidity's [standard JSON output](https://solidity.readthedocs.io/en/v0.5.10/using-the-compiler.html#output-description)
- [x] include source endpoints in AST nodes, and ideally give absolute offsets as `(start, length)`
- [x] deployed source map that follows [Solidity's format](https://solidity.readthedocs.io/en/latest/miscellaneous.html#source-mappings)

**Comment by iamdefinitelyahuman** [comment]
Almost done! Need the following PRs to merge which should fix the failing build on [iamdefinitelyahuman/brownie:vyper](https://github.com/iamdefinitelyahuman/brownie/tree/vyper):

- [ ] https://github.com/vyperlang/vyper/pull/1780
- [ ] https://github.com/vyperlang/vyper/pull/1781

Will also need a new version of Vyper to release before this can be merged.

**Comment by iamdefinitelyahuman** [comment]
Good to go!  Tests passing locally, just waiting on a new Vyper release in a few days!!!

**Comment by jacqueswww** [comment]
![right_on](https://user-images.githubusercontent.com/6917456/71828397-f159f700-30aa-11ea-84cb-b48024b4f225.jpeg)

**Comment by iamdefinitelyahuman** [comment]
Merged in #294
