### ISSUE TITLE
Expose nonce for transactions

### ISSUE THREAD

**Issue by matnad** [iamdefinitelyahuman/brownie#484]
### Overview
Expose the nonce parameter to manually set nonce on deployment and transactions.

Use case: Send multiple transactions in the same block with the `--blockTime [num]` flag for ganache-cli

### Specification
See PR

### Dependencies
Will eventually need `--blockTime` to be exposed as well (separate issue).

**Comment by iamdefinitelyahuman** [comment]
Added in #488
