### ISSUE TITLE
Zombie processes prevent `rpc.attach` from working properly

### ISSUE THREAD

**Issue by tbrent** [iamdefinitelyahuman/brownie#570]
### Environment information

* `brownie` Version: 1.8.9
* `ganache-cli` Version: 6.9.1
* Python Version: 3.8
* OS: osx

### What was wrong?

This is related to #263. I am trying to get a persistent local chain by attaching to an already running 
local `ganache-cli` chain. Here's the error I get when running `network.connect`. 

> Brownie v1.8.9 - Python development framework for Ethereum
> 
> BrownieProject is the active project.
>   File "brownie/_cli/__main__.py", line 58, in main
>     importlib.import_module(f"brownie._cli.{cmd}").main()
>   File "brownie/_cli/run.py", line 43, in main
>     network.connect(CONFIG.argv["network"])
>   File "brownie/network/main.py", line 45, in connect
>     rpc.attach(host)
>   File "brownie/network/rpc.py", line 145, in attach
>     proc = next(i for i in psutil.process_iter() if _check_connections(i, laddr))
>   File "brownie/network/rpc.py", line 145, in <genexpr>
>     proc = next(i for i in psutil.process_iter() if _check_connections(i, laddr))
>   File "brownie/network/rpc.py", line 393, in _check_connections
>     return laddr in [i.laddr for i in proc.connections()]
>   File "psutil/__init__.py", line 1178, in connections
>     return self._proc.connections(kind)
>   File "psutil/_psosx.py", line 334, in wrapper
>     return fun(self, *args, **kwargs)
>   File "psutil/_psosx.py", line 521, in connections
>     rawlist = cext.proc_connections(self.pid, families, types)
>   File "/Users/taylorbrent/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 131, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "psutil/_psosx.py", line 363, in catch_zombie
>     raise ZombieProcess(proc.pid, proc._name, proc._ppid)
> ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=5462)

I've also tried going under the hood and accessing `web3` and `rpc` directly, while using brownie in python package mode. Same ZombieProcess issue. 

### How can it be fixed?

I believe what is happening is that in [this function]( https://github.com/iamdefinitelyahuman/brownie/blob/95cf14a4a24a3c2b079e06fec26d9b592164824c/brownie/network/rpc.py#L391) the iteration is raising a `psutil.ZombieProcess` exception. I think it can be solved by doing something similar to [this](https://stackoverflow.com/a/51990233). 

Happy to provide any other information I can. From looking at recent issues it looks like attaching to a local chain, be it ganache or something else, should work.

**Comment by iamdefinitelyahuman** [comment]
Ahh, this is very useful information! :pray:

The function you flagged was added in #308 to deal with another similar OSX issue..  I guess I didn't fully fix it.  Based on the stackoverflow answer you reference, it probably makes sense to expand this `except` statement to also catch `ZombieProcess` and `NoSuchProcess`.

https://github.com/iamdefinitelyahuman/brownie/blob/95cf14a4a24a3c2b079e06fec26d9b592164824c/brownie/network/rpc.py#L392-L395

I can probably get to this tonight or tomorrow, but if you have time sooner I'll gladly accept a PR :)

**Comment by tbrent** [comment]
I didn't do much more other than add the catches and test it locally to ensure it fixed the issue I was seeing, but here you go!
