### ISSUE TITLE
Compiler - set solc version based on first line of contract

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/brownie#64]
This would be so much simpler than requiring it to be set in the config file, and we could allow for projects to use different compiler versions for different contracts.

**Comment by AndrewBezold** [comment]
When a contract has a floating solidity version pragma, is it preferred to use the lowest available compatible compiler version or the highest?

**Comment by iamdefinitelyahuman** [comment]
I think the highest available version. If the pragma allows it and the user has installed it, to me it seems the logical choice.

**Comment by AndrewBezold** [comment]
I agree. Would it also be good to have it attempt to install whatever version is needed? I've been looking at the solcx code, and I have ideas about how to change that as well to make this change easier and keep the two conceptually different

**Comment by iamdefinitelyahuman** [comment]
If solcx has no compatible version at all, I think it's fine to install the most recent version that fits the pragma.

In a case where there is a compatible version installed locally, but a newer version is available remotely, I don't think it's right to upgrade the local version automatically.  Some people (myself included) avoid using the latest version because...  well, see solc 0.5.5 ahahaha.

It would be cool to have a notification appear when compiling, saying "there is a newer version of solc available, install via xxx".

**Comment by iamdefinitelyahuman** [comment]
re: updates to solcx - i've asked github to change the repo from a fork to a standalone one so that people can open issues.  Until that's happened, it only allows conversations via pull requests so we can either discuss it here or you can open a PR there :)

**Comment by iamdefinitelyahuman** [comment]
Just did a big merge, it includes a method in [compiler.py](https://github.com/HyperLink-Technology/brownie/blob/1a2b0bd96d4ebcc5d11221fa0342b5588f5d8b20/brownie/utils/compiler.py#L36) that should make it easy to integrate the auto-versioning with brownie.
